### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by Lamans007** [Apress/pract-react-native#1]
The code is outdated, could not get it to work.

**Comment by AsimShakour** [comment]
@fzammetti please advise on how to get the code updated or anything else, please. I'd like to give this book to someone as a gift but I am unable to until this is resolved.

thank you so much,
Asim

cc @nancyc15 

here's feedback from another Amazon customer about the book, thanks.
![image](https://user-images.githubusercontent.com/8389291/89142901-56c17980-d50e-11ea-993e-5c08ba98742a.png)

**Comment by fzammetti** [comment]
Hi,

The unfortunate fact is that React Native has changed so much since this book was released that it is now non-trivial to get the code working.  Updating it for the current version would require substantial changes, which would effectively invalidate what's in the book - it might paradoxically be more frustrating to find working code in the repo with explanations in the book that don't match up, especially when they are not minor changes (a tweak here and there might be acceptable, but not the degree of change that would be required now based on the hour or two I spent trying to get it to work with the current release).

The only suggestion I can really think to make is to try and find the same version of React Native as the book was written against so that the examples (should) then work.  

I wish I had a better answer, but the book really effectively needs a second edition with all the updates required at this point.  Of all the books I've written, this one has probably aged the worst thanks to Facebook not especially caring about backward-compatibility apparently.

Sorry I don't have better news, but I'd rather at least be honest with you then try and BS it.
